# -*- coding: utf-8 -*-
"""Projek1_modul

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1afdWQ4Qq3RlRoituPMvVu1bdfTx9Roz3

# Main
"""

from projek1_modul import Transaction

transaksi = Transaction()
transaksi.menu()

"""# Dokumentasi"""

# inisialsisasi instance transaksi
transaksi_1 = Transaction()

# mengosongkan keranjang
transaksi_1.reset_transaction()

# menambah item
transaksi_1.add_items(['bakso', 5, 13_000])
transaksi_1.add_items(['soto', 3, 8_000])

# show keranjang
transaksi_1.check_order()

# membuat output sesuai test case
transaksi_1.test_case_output()

# mengosongkan keranjang
transaksi_1.reset_transaction()